### ISSUE TITLE
reaches waiting for seed to grow then stop

### ISSUE THREAD

**Issue by MohammadxCoder** [robokop92/SeedBreeder#1]
as title... it reach waiting for seed to grow then stop. and error appear ...
![screen shot 2016-07-19 at 8 14 30 pm](https://cloud.githubusercontent.com/assets/17279296/16959423/bd8784fe-4ded-11e6-96d4-7453953be1c6.png)

**Comment by robokop92** [comment]
Take a picture of your setup and the F3 screen.

**Comment by LordStrainer** [comment]
I had that problem to, but then I realized that I didn't set this up facing the right cardinal directions (North, East, West, South), so setting it up the way it says [here](https://github.com/robokop92/SeedBreeder/wiki/How-to-use-the-ComputerCraft-Version) seemed to fix it for me at least.

**Comment by MohammadxCoder** [comment]
LordStrainer... "facing the right cardinal directions " for the turtle ???
and robokop92 ... i will take screenshot

**Comment by MohammadxCoder** [comment]
now it work .... i think i did the set up wrong first time ... 
thank you

**Comment by robokop92** [comment]
The setup must face the right direction for this to work (ex. the Trash Can must always be in the north-east corner)

**Comment by MohammadxCoder** [comment]
you can close it.... i re-do it again ... like what you say... and it work :)
